### ISSUE TITLE
How do I download this app?

### ISSUE THREAD

**Issue by cr7users** [joshckar/Notepad-#1]
Hello 

How do I download this app?

**Comment by NexNoir** [comment]
Hello, you can visit our Telegram channel https://t.me/Notepad3 and download from there
Thanks

**Comment by cr7users** [comment]
Thanks

**Comment by cr7users** [comment]
Hello, go to the upper part and select format from the menu
and choose font and choose your desired font and size from there
Thanks from our team♥
