### ISSUE TITLE
 change the font

### ISSUE THREAD

**Issue by chengeryoungr** [joshckar/Notepad-#2]
How can I change the font?

**Comment by NexNoir** [comment]
Hello, go to the upper part and select format from the menu
and choose font and choose your desired font and size from there
Thanks from our team♥

**Comment by chengeryoungr** [comment]
Thank you

**Comment by chengeryoungr** [comment]
excuse me I have a question again
can I ask you?

**Comment by NexNoir** [comment]
yes

**Comment by chengeryoungr** [comment]
How can I become a member of your Telegram channel?

**Comment by NexNoir** [comment]
Hello first go to  upper part (Help) second part (Abut) then join to Telegram channel
Thanks from our team♥

**Comment by chengeryoungr** [comment]
Thank you so much .....
